In [1]:
import tensorflow as tf

In [4]:
input_ds = tf.data.Dataset.list_files('./reviews/*/*', shuffle=False)

In [8]:
for i in input_ds:
    print(i)

tf.Tensor(b'.\\reviews\\negative\\neg_1.txt', shape=(), dtype=string)
tf.Tensor(b'.\\reviews\\negative\\neg_2.txt', shape=(), dtype=string)
tf.Tensor(b'.\\reviews\\negative\\neg_3.txt', shape=(), dtype=string)
tf.Tensor(b'.\\reviews\\positive\\pos_1.txt', shape=(), dtype=string)
tf.Tensor(b'.\\reviews\\positive\\pos_2.txt', shape=(), dtype=string)
tf.Tensor(b'.\\reviews\\positive\\pos_3.txt', shape=(), dtype=string)


In [27]:
def get_label(file_path):
    import os
    label = tf.strings.split(file_path, os.sep)[-2]
    return label

In [28]:
get_label('\\reviews\\negative\\neg_1.txt')

<tf.Tensor: shape=(), dtype=string, numpy=b'negative'>

In [29]:
def get_texts(file_path):
    label = get_label(file_path)
    text = tf.io.read_file(file_path)
    return text, label

In [30]:
train_ds = input_ds.map(get_texts)

In [31]:
for i in train_ds.take(1):
    print(i)

(<tf.Tensor: shape=(), dtype=string, numpy=b"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them.\r\n">, <tf.Tensor: shape=(), dtype=string, numpy=b'negative'>)


In [34]:
train_ds = train_ds.filter(lambda x, y: x!="")
len(list(train_ds))

4

# Solution

In [37]:
train_ds = input_ds.map(get_texts).filter(lambda x,y: x!="").shuffle(4)

In [46]:
for text, label in train_ds.as_numpy_iterator():
    print(text[:10], label)

b'One of the' b'positive'
b'This show ' b'negative'
b'Basically ' b'negative'
b'A wonderfu' b'positive'
